# Generated by Django 2.1 on 2019-01-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='users',
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
