# Generated by Django 2.1 on 2019-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190104_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed_to',
            field=models.ManyToManyField(related_name='subscribed_by', to='users.Profile'),
        ),
    ]
